language: java
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk6
script: mvn -X cobertura:cobertura coveralls:report
notifications:
   email: false
after_success:
  - mvn -X clean cobertura:cobertura coveralls:report