language: java
jdk:
  - oraclejdk8
  - openjdk7

notifications:
  email: false

install: mvn install -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6 -DskipTests=true
script: mvn test -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6

after_success:
   - mvn -X clean cobertura:cobertura coveralls:cobertura
