language: java
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk6
script: mvn cobertura:cobertura coveralls:report
notifications:
   email: false
after_success:
  - mvn -x clean cobertura:cobertura coveralls:report